### ISSUE TITLE
First line is indented if it ends in a colon

### ISSUE THREAD

**Issue by wwentland** [glynnforrest/salt-mode#4]
When entering the following content `yaml-mode` currently indents wrongly.

```
--- expected
foo:
  - bar: baz
  - foo: 1
--- yaml-mode
foo:
  - bar: baz
    - foo: 1
--- salt-mode
  foo:
    - bar: baz
      - foo: 1
```
The indentation of sequence elements seems to be broken in `yaml-mode` also (cf.     https://github.com/yoshiki/yaml-mode/issues/49) but the incorrect indentation of the first line appears to be specific to `salt-mode` and is rather irritating given that a SLS often starts like that :)
